### PR TITLE
Update FUtil.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by AvalancheYT** [comment]
You are missing the quotation marks around your name.

**Comment by DUFCLiam** [comment]
Sorry, I was very tired.

**Comment by DUFCLiam** [comment]
@AvalancheYT or @Loooll

**Comment by AvalancheYT** [comment]
I am sorry but I do not work on this. I am just helping out.

**Comment by DUFCLiam** [comment]
Oh, Alright .

**Comment by Mafrans** [comment]
@Loooll is the only one with the ability to allow pull requests.
Please close this request as i merged it with mine.

**Pull request closed without merging**
